name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    container: node:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          npm install
          ls -l
          ./node_modules/.bin/eslint src/detai.jsx
          eslint src/list.jsx
          eslint src/server.js
          eslint src/server2.js
  