name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    container: node:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          npm cache clean
          npm install
          npm run jslint
          npm run jsxlint
  