name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    container: node:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          cd backend
          npm install
          eslint app.js
          eslint server.js
          eslint actions
          # npm run jsxlint
          # npm run jslint
          
  
