name: CI on Push and PullRequest

on: [push, pull_request]

jobs:
  ci:
    container: node:latest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          cd frontend
          npm install
          sl -al
          ls -al
          which eslint
          eslint src/index.jsx
          # npm run jsxlint
          # npm run jslint
          
  
